name: Local Registry
description: |
  local registry with UI.
version: v0.0.2
category: Web
maintainer: Sean Zhang
license: The MIT license
projectURL: https://github.com/zhangsean/rancher-catalog.git
