version: '2'
services:
  registry:
    image: registry
    stdin_open: true
    volumes:
    - /opt/registry:/var/lib/docker/registry
    tty: true
    ports:
    - ${REGISTRY_ADDR_PORT}:5000/tcp
  registry-ui:
    image: zhangsean/tiny-registry-ui
    environment:
      REGISTRY_WEB: ${REGISTRY_ADDR}
      REGISTRY_API: http://registry:5000/v2
    stdin_open: true
    tty: true
    links:
    - registry:registry
    ports:
    - ${REGISTRY_UI_PORT}:80/tcp
